//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSConsoleTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ru:ifmo:pellet:apiws:baseWS", ConfigurationName="ServiceReference1.PelletAPIInterface")]
    public interface PelletAPIInterface {
        
        // CODEGEN: Generating message contract since the operation executeQuery is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSConsoleTest.ServiceReference1.executeQueryResponse1 executeQuery(WSConsoleTest.ServiceReference1.executeQueryRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ru:ifmo:pellet:apiws:baseWS")]
    public partial class executeQueryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] sparqlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] sparql {
            get {
                return this.sparqlField;
            }
            set {
                this.sparqlField = value;
                this.RaisePropertyChanged("sparql");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ru:ifmo:pellet:apiws:baseWS")]
    public partial class executeQueryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] xMLResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] XMLResult {
            get {
                return this.xMLResultField;
            }
            set {
                this.xMLResultField = value;
                this.RaisePropertyChanged("XMLResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeQueryRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ru:ifmo:pellet:apiws:baseWS", Order=0)]
        public WSConsoleTest.ServiceReference1.executeQueryRequest executeQueryRequest;
        
        public executeQueryRequest1() {
        }
        
        public executeQueryRequest1(WSConsoleTest.ServiceReference1.executeQueryRequest executeQueryRequest) {
            this.executeQueryRequest = executeQueryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeQueryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ru:ifmo:pellet:apiws:baseWS", Order=0)]
        public WSConsoleTest.ServiceReference1.executeQueryResponse executeQueryResponse;
        
        public executeQueryResponse1() {
        }
        
        public executeQueryResponse1(WSConsoleTest.ServiceReference1.executeQueryResponse executeQueryResponse) {
            this.executeQueryResponse = executeQueryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PelletAPIInterfaceChannel : WSConsoleTest.ServiceReference1.PelletAPIInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PelletAPIInterfaceClient : System.ServiceModel.ClientBase<WSConsoleTest.ServiceReference1.PelletAPIInterface>, WSConsoleTest.ServiceReference1.PelletAPIInterface {
        
        public PelletAPIInterfaceClient() {
        }
        
        public PelletAPIInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PelletAPIInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PelletAPIInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PelletAPIInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsoleTest.ServiceReference1.executeQueryResponse1 WSConsoleTest.ServiceReference1.PelletAPIInterface.executeQuery(WSConsoleTest.ServiceReference1.executeQueryRequest1 request) {
            return base.Channel.executeQuery(request);
        }
        
        public WSConsoleTest.ServiceReference1.executeQueryResponse executeQuery(WSConsoleTest.ServiceReference1.executeQueryRequest executeQueryRequest) {
            WSConsoleTest.ServiceReference1.executeQueryRequest1 inValue = new WSConsoleTest.ServiceReference1.executeQueryRequest1();
            inValue.executeQueryRequest = executeQueryRequest;
            WSConsoleTest.ServiceReference1.executeQueryResponse1 retVal = ((WSConsoleTest.ServiceReference1.PelletAPIInterface)(this)).executeQuery(inValue);
            return retVal.executeQueryResponse;
        }
    }
}
