PREFIX nasis: <http://escience.ifmo.ru/ipse/nasis.owl#>
PREFIX escience: <http://escience.ifmo.ru/ipse/escience.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?M ?L ?Q
WHERE {
  ?M escience:methodQuality ?Q. 
  OPTIONAL {?M rdfs:label ?L} .
  FILTER (xsd:float(?Q) > 0.9)
}
