PREFIX nasis: <http://escience.ifmo.ru/ipse/nasis.owl#>
PREFIX escience: <http://escience.ifmo.ru/ipse/escience.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?FILE_TYPE
WHERE {
  ?FILE_TYPE rdf:type escience:FileType
}
