//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSConsoleTest.JSimpCalcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.calc/", ConfigurationName="JSimpCalcRef.JSimpCalcWebService")]
    public interface JSimpCalcWebService {
        
        // CODEGEN: Контракт генерации сообщений с именем return из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/JSimpCalcWebService/powerRequest", ReplyAction="http://ws.calc/JSimpCalcWebService/powerResponse")]
        WSConsoleTest.JSimpCalcRef.powerResponse power(WSConsoleTest.JSimpCalcRef.powerRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем return из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/JSimpCalcWebService/minimumRequest", ReplyAction="http://ws.calc/JSimpCalcWebService/minimumResponse")]
        WSConsoleTest.JSimpCalcRef.minimumResponse minimum(WSConsoleTest.JSimpCalcRef.minimumRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем return из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/JSimpCalcWebService/additionRequest", ReplyAction="http://ws.calc/JSimpCalcWebService/additionResponse")]
        WSConsoleTest.JSimpCalcRef.additionResponse addition(WSConsoleTest.JSimpCalcRef.additionRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем return из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/JSimpCalcWebService/subtractionRequest", ReplyAction="http://ws.calc/JSimpCalcWebService/subtractionResponse")]
        WSConsoleTest.JSimpCalcRef.subtractionResponse subtraction(WSConsoleTest.JSimpCalcRef.subtractionRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем return из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/JSimpCalcWebService/multiplicationRequest", ReplyAction="http://ws.calc/JSimpCalcWebService/multiplicationResponse")]
        WSConsoleTest.JSimpCalcRef.multiplicationResponse multiplication(WSConsoleTest.JSimpCalcRef.multiplicationRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем return из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/JSimpCalcWebService/divisionRequest", ReplyAction="http://ws.calc/JSimpCalcWebService/divisionResponse")]
        WSConsoleTest.JSimpCalcRef.divisionResponse division(WSConsoleTest.JSimpCalcRef.divisionRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем return из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/JSimpCalcWebService/maximumRequest", ReplyAction="http://ws.calc/JSimpCalcWebService/maximumResponse")]
        WSConsoleTest.JSimpCalcRef.maximumResponse maximum(WSConsoleTest.JSimpCalcRef.maximumRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class powerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="power", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.powerRequestBody Body;
        
        public powerRequest() {
        }
        
        public powerRequest(WSConsoleTest.JSimpCalcRef.powerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class powerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double parameter1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double parameter2;
        
        public powerRequestBody() {
        }
        
        public powerRequestBody(double parameter1, double parameter2) {
            this.parameter1 = parameter1;
            this.parameter2 = parameter2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class powerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="powerResponse", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.powerResponseBody Body;
        
        public powerResponse() {
        }
        
        public powerResponse(WSConsoleTest.JSimpCalcRef.powerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class powerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public powerResponseBody() {
        }
        
        public powerResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class minimumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="minimum", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.minimumRequestBody Body;
        
        public minimumRequest() {
        }
        
        public minimumRequest(WSConsoleTest.JSimpCalcRef.minimumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class minimumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double parameter1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double parameter2;
        
        public minimumRequestBody() {
        }
        
        public minimumRequestBody(double parameter1, double parameter2) {
            this.parameter1 = parameter1;
            this.parameter2 = parameter2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class minimumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="minimumResponse", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.minimumResponseBody Body;
        
        public minimumResponse() {
        }
        
        public minimumResponse(WSConsoleTest.JSimpCalcRef.minimumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class minimumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public minimumResponseBody() {
        }
        
        public minimumResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class additionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addition", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.additionRequestBody Body;
        
        public additionRequest() {
        }
        
        public additionRequest(WSConsoleTest.JSimpCalcRef.additionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class additionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double parameter1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double parameter2;
        
        public additionRequestBody() {
        }
        
        public additionRequestBody(double parameter1, double parameter2) {
            this.parameter1 = parameter1;
            this.parameter2 = parameter2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class additionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="additionResponse", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.additionResponseBody Body;
        
        public additionResponse() {
        }
        
        public additionResponse(WSConsoleTest.JSimpCalcRef.additionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class additionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public additionResponseBody() {
        }
        
        public additionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class subtractionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="subtraction", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.subtractionRequestBody Body;
        
        public subtractionRequest() {
        }
        
        public subtractionRequest(WSConsoleTest.JSimpCalcRef.subtractionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class subtractionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double parameter1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double parameter2;
        
        public subtractionRequestBody() {
        }
        
        public subtractionRequestBody(double parameter1, double parameter2) {
            this.parameter1 = parameter1;
            this.parameter2 = parameter2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class subtractionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="subtractionResponse", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.subtractionResponseBody Body;
        
        public subtractionResponse() {
        }
        
        public subtractionResponse(WSConsoleTest.JSimpCalcRef.subtractionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class subtractionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public subtractionResponseBody() {
        }
        
        public subtractionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class multiplicationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="multiplication", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.multiplicationRequestBody Body;
        
        public multiplicationRequest() {
        }
        
        public multiplicationRequest(WSConsoleTest.JSimpCalcRef.multiplicationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class multiplicationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double parameter1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double parameter2;
        
        public multiplicationRequestBody() {
        }
        
        public multiplicationRequestBody(double parameter1, double parameter2) {
            this.parameter1 = parameter1;
            this.parameter2 = parameter2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class multiplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="multiplicationResponse", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.multiplicationResponseBody Body;
        
        public multiplicationResponse() {
        }
        
        public multiplicationResponse(WSConsoleTest.JSimpCalcRef.multiplicationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class multiplicationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public multiplicationResponseBody() {
        }
        
        public multiplicationResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class divisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="division", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.divisionRequestBody Body;
        
        public divisionRequest() {
        }
        
        public divisionRequest(WSConsoleTest.JSimpCalcRef.divisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class divisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double parameter1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double parameter2;
        
        public divisionRequestBody() {
        }
        
        public divisionRequestBody(double parameter1, double parameter2) {
            this.parameter1 = parameter1;
            this.parameter2 = parameter2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class divisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="divisionResponse", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.divisionResponseBody Body;
        
        public divisionResponse() {
        }
        
        public divisionResponse(WSConsoleTest.JSimpCalcRef.divisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class divisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public divisionResponseBody() {
        }
        
        public divisionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class maximumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="maximum", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.maximumRequestBody Body;
        
        public maximumRequest() {
        }
        
        public maximumRequest(WSConsoleTest.JSimpCalcRef.maximumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class maximumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double parameter1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double parameter2;
        
        public maximumRequestBody() {
        }
        
        public maximumRequestBody(double parameter1, double parameter2) {
            this.parameter1 = parameter1;
            this.parameter2 = parameter2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class maximumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="maximumResponse", Namespace="http://ws.calc/", Order=0)]
        public WSConsoleTest.JSimpCalcRef.maximumResponseBody Body;
        
        public maximumResponse() {
        }
        
        public maximumResponse(WSConsoleTest.JSimpCalcRef.maximumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class maximumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public maximumResponseBody() {
        }
        
        public maximumResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JSimpCalcWebServiceChannel : WSConsoleTest.JSimpCalcRef.JSimpCalcWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JSimpCalcWebServiceClient : System.ServiceModel.ClientBase<WSConsoleTest.JSimpCalcRef.JSimpCalcWebService>, WSConsoleTest.JSimpCalcRef.JSimpCalcWebService {
        
        public JSimpCalcWebServiceClient() {
        }
        
        public JSimpCalcWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JSimpCalcWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JSimpCalcWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JSimpCalcWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsoleTest.JSimpCalcRef.powerResponse WSConsoleTest.JSimpCalcRef.JSimpCalcWebService.power(WSConsoleTest.JSimpCalcRef.powerRequest request) {
            return base.Channel.power(request);
        }
        
        public string power(double parameter1, double parameter2) {
            WSConsoleTest.JSimpCalcRef.powerRequest inValue = new WSConsoleTest.JSimpCalcRef.powerRequest();
            inValue.Body = new WSConsoleTest.JSimpCalcRef.powerRequestBody();
            inValue.Body.parameter1 = parameter1;
            inValue.Body.parameter2 = parameter2;
            WSConsoleTest.JSimpCalcRef.powerResponse retVal = ((WSConsoleTest.JSimpCalcRef.JSimpCalcWebService)(this)).power(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsoleTest.JSimpCalcRef.minimumResponse WSConsoleTest.JSimpCalcRef.JSimpCalcWebService.minimum(WSConsoleTest.JSimpCalcRef.minimumRequest request) {
            return base.Channel.minimum(request);
        }
        
        public string minimum(double parameter1, double parameter2) {
            WSConsoleTest.JSimpCalcRef.minimumRequest inValue = new WSConsoleTest.JSimpCalcRef.minimumRequest();
            inValue.Body = new WSConsoleTest.JSimpCalcRef.minimumRequestBody();
            inValue.Body.parameter1 = parameter1;
            inValue.Body.parameter2 = parameter2;
            WSConsoleTest.JSimpCalcRef.minimumResponse retVal = ((WSConsoleTest.JSimpCalcRef.JSimpCalcWebService)(this)).minimum(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsoleTest.JSimpCalcRef.additionResponse WSConsoleTest.JSimpCalcRef.JSimpCalcWebService.addition(WSConsoleTest.JSimpCalcRef.additionRequest request) {
            return base.Channel.addition(request);
        }
        
        public string addition(double parameter1, double parameter2) {
            WSConsoleTest.JSimpCalcRef.additionRequest inValue = new WSConsoleTest.JSimpCalcRef.additionRequest();
            inValue.Body = new WSConsoleTest.JSimpCalcRef.additionRequestBody();
            inValue.Body.parameter1 = parameter1;
            inValue.Body.parameter2 = parameter2;
            WSConsoleTest.JSimpCalcRef.additionResponse retVal = ((WSConsoleTest.JSimpCalcRef.JSimpCalcWebService)(this)).addition(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsoleTest.JSimpCalcRef.subtractionResponse WSConsoleTest.JSimpCalcRef.JSimpCalcWebService.subtraction(WSConsoleTest.JSimpCalcRef.subtractionRequest request) {
            return base.Channel.subtraction(request);
        }
        
        public string subtraction(double parameter1, double parameter2) {
            WSConsoleTest.JSimpCalcRef.subtractionRequest inValue = new WSConsoleTest.JSimpCalcRef.subtractionRequest();
            inValue.Body = new WSConsoleTest.JSimpCalcRef.subtractionRequestBody();
            inValue.Body.parameter1 = parameter1;
            inValue.Body.parameter2 = parameter2;
            WSConsoleTest.JSimpCalcRef.subtractionResponse retVal = ((WSConsoleTest.JSimpCalcRef.JSimpCalcWebService)(this)).subtraction(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsoleTest.JSimpCalcRef.multiplicationResponse WSConsoleTest.JSimpCalcRef.JSimpCalcWebService.multiplication(WSConsoleTest.JSimpCalcRef.multiplicationRequest request) {
            return base.Channel.multiplication(request);
        }
        
        public string multiplication(double parameter1, double parameter2) {
            WSConsoleTest.JSimpCalcRef.multiplicationRequest inValue = new WSConsoleTest.JSimpCalcRef.multiplicationRequest();
            inValue.Body = new WSConsoleTest.JSimpCalcRef.multiplicationRequestBody();
            inValue.Body.parameter1 = parameter1;
            inValue.Body.parameter2 = parameter2;
            WSConsoleTest.JSimpCalcRef.multiplicationResponse retVal = ((WSConsoleTest.JSimpCalcRef.JSimpCalcWebService)(this)).multiplication(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsoleTest.JSimpCalcRef.divisionResponse WSConsoleTest.JSimpCalcRef.JSimpCalcWebService.division(WSConsoleTest.JSimpCalcRef.divisionRequest request) {
            return base.Channel.division(request);
        }
        
        public string division(double parameter1, double parameter2) {
            WSConsoleTest.JSimpCalcRef.divisionRequest inValue = new WSConsoleTest.JSimpCalcRef.divisionRequest();
            inValue.Body = new WSConsoleTest.JSimpCalcRef.divisionRequestBody();
            inValue.Body.parameter1 = parameter1;
            inValue.Body.parameter2 = parameter2;
            WSConsoleTest.JSimpCalcRef.divisionResponse retVal = ((WSConsoleTest.JSimpCalcRef.JSimpCalcWebService)(this)).division(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsoleTest.JSimpCalcRef.maximumResponse WSConsoleTest.JSimpCalcRef.JSimpCalcWebService.maximum(WSConsoleTest.JSimpCalcRef.maximumRequest request) {
            return base.Channel.maximum(request);
        }
        
        public string maximum(double parameter1, double parameter2) {
            WSConsoleTest.JSimpCalcRef.maximumRequest inValue = new WSConsoleTest.JSimpCalcRef.maximumRequest();
            inValue.Body = new WSConsoleTest.JSimpCalcRef.maximumRequestBody();
            inValue.Body.parameter1 = parameter1;
            inValue.Body.parameter2 = parameter2;
            WSConsoleTest.JSimpCalcRef.maximumResponse retVal = ((WSConsoleTest.JSimpCalcRef.JSimpCalcWebService)(this)).maximum(inValue);
            return retVal.Body.@return;
        }
    }
}
